routes/web.php
<?php

use App\Http\Controllers\Admin\PostController as AdminPostController;
use App\Http\Controllers\DashboardController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use SebastianBergmann\CodeCoverage\Report\Html\Dashboard;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/',[PostController::class, 'index'])->name('posts.index');

Route::middleware(['auth'])->group(function(){

    Route::resource('posts', PostController::class)->except('index');

    Route::get('/dashboard',[DashboardController::class, 'index'])->name('dashboard');

    Route::middleware(['admin'])->name('admin.')->prefix('admin')->group(function(){

        Route::resource('posts', AdminPostController::class);

    });
});




// Route::get('/', function () {
//     return view('welcome');
// });



require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

            @if(session('success'))
                {{session('success')}}
            @endif
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                @foreach($posts as $post)
                    <div class="flex items-center">
                        <a href="{{route('posts.edit', $post)}}" class="bg-yellow-500 px-2 py-3 block">Editer{{$post->title}}</a>
                        <a href="#" class="bg-red-500 px-2 py-3 block"
                         onclick="event.preventDefault;
                            document.getElementById('destroy-post-form').submit();
                            ">
                            Supprimer{{$post->title}}
                           <form action="{{ route('posts.destroy', $post) }}" method="post" id="destroy-post-form">
                            @csrf
                            @method('delete')
                           </form>
                        </a>
                    </div>

                @endforeach
            </div>
        </div>
    </div>
</x-app-layout>