routes/web.php
<?php

use App\Http\Controllers\Admin\PostController as AdminPostController;
use App\Http\Controllers\DashboardController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use SebastianBergmann\CodeCoverage\Report\Html\Dashboard;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/',[PostController::class, 'index'])->name('posts.index');

Route::middleware(['auth'])->group(function(){

    Route::resource('posts', PostController::class)->except('index');

    Route::get('/dashboard',[DashboardController::class, 'index'])->name('dashboard');

    Route::middleware(['admin'])->name('admin.')->prefix('admin')->group(function(){

        Route::resource('posts', AdminPostController::class);

    });
});




// Route::get('/', function () {
//     return view('welcome');
// });



require __DIR__.'/auth.php';

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Post extends Model
{
    use HasFactory;

    protected $guarded = [];

    public static function boot(){
        //cette methode va servir a associe notre nouveau post a ces parents user_id et categorie_id lors de la soumission du for create
        parent::boot();

        self::creating(function($post){
            $post->user()->associate(auth()->user()->id);
            $post->category()->associate(request()->category);
        });
        

        // self::updating(function($post){
        //     $post->category()->associate(request()->category);
        // });
    }

    public function user(){
        return $this ->belongsTo(User::class);
    }
    public function category(){
        return $this ->belongsTo(Category::class);
    }
    public function getTitleAttribute($attribute){
        return Str::title($attribute);
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Actions\PostUpdateAction;
use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();

        return view('admin.post.index', compact('posts'));
       
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
       
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
        $categories =  Category::all();

        return view('admin.post.edit',compact('post','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        //
        $arrayUpdate = [
            'title' => $request->title,
            'content'   => $request->content
           ];
    
           if($request->image !== null) {
            $imageName = $request->image->store('posts');
           $arrayUpdate = array_merge($arrayUpdate, ['image'=> $imageName ]);
        }
    
           $post->update($arrayUpdate);

           return redirect()->route('admin.posts.index')->with('success', 'Le post a ete modifie');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        //
        $post->delete();
        return redirect()->route('admin.posts.index')->with('success','Le post a ete supprimer');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\Category;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Gate;
use App\Http\Requests\StorePostRequest;
use App\Http\Requests\UpdatePostRequest;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $posts = Post::all(); cette requete envoie simultanement 50 requetes
        $posts = Post::with('category','user')->latest()->get();
       return view('post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categories = Category::all();

        return view('post.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StorePostRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePostRequest $request)
    {
        // au niveau de store posts fait reference au nom de dossier qui sera creer au niveau du app public 
        $imageName = $request->image->store('posts');
        Post::create(
            [
                'title'=> $request->title,
                'content'=> $request->content,
                'image'=> $imageName,
                
            ]);   
            
            return redirect()->route('dashboard')->with('success','Votre post a ete cree');
        }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //

        return view('post.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        if (! Gate::allows('update-post', $post)) {
            abort(403);
        }
 
        //
        $categories = Category::all();
        return view('post.edit',compact('post','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdatePostRequest  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(StorePostRequest $request, Post $post)
    {
        //
      
       $arrayUpdate = [
        'title' => $request->title,
        'content'   => $request->content
       ];

       $post->category()->associate(Category::find($request->category));

       if($request->image !== null) {
        $imageName = $request->image->store('posts');
       $arrayUpdate = array_merge($arrayUpdate, ['image'=> $imageName ]);
    }

       $post->update($arrayUpdate);

       return redirect()->route('dashboard')->with('success','Votre post a ete modifie');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        //
        if (! Gate::allows('destroy-post', $post)) {
            abort(403);
        }

        $post->delete();

        return redirect()->route('dashboard')->with('success','Votre post a ete supprimer');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/post/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Editer Post Title') }}
        </h2>
    </x-slot>

<!-- component -->
    <div class="max-w-4xl px-10 py-6 mx-auto bg-white rounded-lg shadow-md">
        @foreach($errors->all() as $error)
        <div class="my-5">
        <span class="block text-red-500">{{$error}}</span>  
        </div>
        @endforeach
        
        <form action="{{route('admin.posts.update', $post)}}" method="post" enctype="multipart/form-data" class="mt-10">
            @method('put')
            @csrf

            <x-label for="title" value="Titre du post" />
            <x-input id="title" name="title" value="{{$post->title}}"/>

            <x-label for="title" value="Contenue du post" />
            <textarea name="content" id="content" cols="30" rows="10">
            {{  $post->content  }}
            </textarea>

            <x-label for="image" value="image du post" />
            <x-input id="image" type="file" name="image"/>

            <x-label for="category" value="Categorie du post" />
            <select name="category" id="category">
                @foreach($categories as $category)
                <option value="{{   $category->id   }}"{{ $post->category_id === $category->id ? 'selected' : ''}}>{{$category->name }}</option>
                @endforeach
            </select>
            <x-button style="display : block !important;" class="mt-5">Modifier mon post</x-button>
        </form>      
    </div>
</x-app-layout>

resources/views/admin/post/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Admin Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

            @if(session('success'))
                {{session('success')}}
            @endif
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                @foreach($posts as $post)
                    <div class="flex items-center">
                        <a href="{{route('admin.posts.edit', $post)}}" class="bg-yellow-500 px-2 py-3 block">Editer{{$post->title}}</a>
                        <a href="#" class="bg-red-500 px-2 py-3 block"
                         onclick="event.preventDefault;
                            document.getElementById('destroy-post-form').submit();
                            ">
                            Supprimer{{$post->title}}
                           <form action="{{ route('admin.posts.destroy', $post) }}" method="post" id="destroy-post-form">
                            @csrf
                            @method('delete')
                           </form>
                        </a>
                    </div>

                @endforeach
            </div>
        </div>
    </div>
</x-app-layout>